### ISSUE TITLE
spocr build not working

### ISSUE THREAD

**Issue by fen89** [nuetzliches/spocr#10]
Spocr build (with or without -`-dry-run` flag throws an exception):

```
> spocr build -d
Build as dry run.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SpocR.Internal.Common.CommandLineInterfaceConfiguration.OnBuild(CommandLineInterface cli, Boolean dryrun) in C:\temp\spocr\src\Internal\Common\CommandLineInterface.cs:line 313
   at SpocR.Internal.Common.CommandLineInterfaceConfiguration.<>c__DisplayClass0_3.<Configure>b__8() in C:\temp\spocr\src\Internal\Common\CommandLineInterface.cs:line 89
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplicationExtensions.cs:line 117
   at SpocR.Program.Main(String[] args) in C:\temp\spocr\src\Program.cs:line 15
```

**Comment by fen89** [comment]
New namespace config was missing in a prior config. Make sure to setup a config like the following in the spocr.json.

- Node `Role` needs to be present
- `Params` inside node `Structure -> Children` needs to be present

```
[...]
  "Project": {
    "Namespace": "...",
    "Role": {
      "Kind": "Default"
    },
    "DataBase": {
      "ConnectionString": "..."
    },
    "Structure": [
      {
        "Name": "DataContext",
        "Path": "./DataContext",
        "Children": [
          {
            "Name": "Models",
            "Path": "./DataContext/Models"
          },
          {
            "Name": "Params",
            "Path": "./DataContext/Params"
          },
          {
            "Name": "StoredProcedures",
            "Path": "./DataContext/StoredProcedures"
          }
        ]
      }
    ]
  },
[...]
```
