### ISSUE TITLE
Display only a warning if config "WithUserId" is violated

### ISSUE THREAD

**Issue by fen89** [nuetzliches/spocr#46]
**Describe the bug**
At the moment SpocR throws an exception if there exists one stored procedure which violates the principle @UserId as first parameter if the config option WithUserIdis set. The problem here is that we a) can not determine which procedure throws the exception and b) spocr terminates and doesn't generate all following models and methods.

**To Reproduce**

- Make sure your spocr.json contains

```json
"Project": {
  "Identity": {
   "Kind": "WithUserId"
  }
}
```

- Make sure you have at least one stored procedure which doesnt have @UserId param at first place.
    Run spocr rebuild

```
CodeBase generated in 806 ms.
DataContextModels generated in 96 ms.
DataContextParams generated in 18 ms.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The StoredProcedure `OrgaList` requires a first Parameter with Name `@UserId`
   at SpocR.Generator.GetStoredProcedureText(Schema schema, List`1 storedProcedures) in \src\Generator.cs:line 393
   at SpocR.Generator.GenerateDataContextStoredProcedures(Boolean dryrun) in \src\Generator.cs:line 541
   at SpocR.Managers.SpocrManager.Build(Boolean dryRun) in \spocr\src\Managers\SpocrManager.cs:line 267
   at SpocR.Commands.RebuildCommand.OnExecute() in \src\Commands\RebuildCommand.cs:line 22
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 86
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 64
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at SpocR.Program.Main(String[] args) in \src\Program.cs:line 61
```

**Expected behavior**
Print out a warning which stored procedures violate the config and continue execution without throwing an exception.

**Version**

- SpocR Version 1.1.7.4

**Comment by fen89** [comment]
implemented in v1.2
