### ISSUE TITLE
Unhandled exception if there exist SPs with custom naming

### ISSUE THREAD

**Issue by fen89** [nuetzliches/spocr#8]
`spocr pull` throws an internal exception if there exist Stored Procedures on the DB with a custom naming.

e.g.: SP `CustomerPdf` instead of `CustomerPdfList`

spocr should instead skip them and maybe print out a warning.

```
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at SpocR.Internal.Common.Definitions.StoredProcedureDefinition.get_EntityName() in spocr\src\Internal\Common\Definitions.cs:line 97
   at SpocR.Internal.Common.Engine.<>c.<GenerateDataContextStoredProcedures>b__21_2(StoredProcedureDefinition i) in spocr\src\Internal\Common\Engine.cs:line 432
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedResultEnumerable`3.GetEnumerator()
   at SpocR.Internal.Common.Engine.GenerateDataContextStoredProcedures() in spocr\src\Internal\Common\Engine.cs:line 432
   at SpocR.Internal.Common.CommandLineInterfaceConfiguration.<>c__DisplayClass0_0.<Configure>b__10() in spocr\src\Internal\Common\CommandLineInterface.cs:line 184
   at SpocR.Internal.Common.CommandLineInterface.Execute(String[] args) in spocr\src\Internal\Common\CommandLineInterface.cs:line 41
   at SpocR.Program.Main(String[] args) in spocr\src\Program.cs:line 23

```

**Comment by 7schmiede** [comment]
Per design spocr is depending on a naming scheme.
We have to know about the Entity, Action and Addons.
The Entity is for building namespaces, folders and objects.
The Action is for creating the models (Crud-Result, Single, List, JSON-String).

So in this case we can only print a warning and disable the StoredProcedure-Building in spocr.json.
